export type City = {
  slug: string;
  name: string;
  namePrepositional: string;
  nameGenitive: string;
  oblast: string;
  oblastGenitive: string;
  coords: {
    lat: number;
    lng: number;
  };
  districts?: string[];
  population?: number;
};

export const cities: City[] = [
  {
    slug: "gomel",
    name: "Гомель",
    namePrepositional: "Гомеле",
    nameGenitive: "Гомеля",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.4345, lng: 30.9754 },
    districts: ["Центральный", "Советский", "Железнодорожный", "Новобелицкий"],
    population: 501000,
  },
  {
    slug: "mozyr",
    name: "Мозырь",
    namePrepositional: "Мозыре",
    nameGenitive: "Мозыря",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.0495, lng: 29.2456 },
    population: 108000,
  },
  {
    slug: "zhlobin",
    name: "Жлобин",
    namePrepositional: "Жлобине",
    nameGenitive: "Жлобина",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.8926, lng: 30.024 },
    population: 75000,
  },
  {
    slug: "svetlogorsk",
    name: "Светлогорск",
    namePrepositional: "Светлогорске",
    nameGenitive: "Светлогорска",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.6333, lng: 29.7333 },
    population: 64000,
  },
  {
    slug: "rechitsa",
    name: "Речица",
    namePrepositional: "Речице",
    nameGenitive: "Речицы",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.3617, lng: 30.3916 },
    population: 61000,
  },
  {
    slug: "kalinkovichi",
    name: "Калинковичи",
    namePrepositional: "Калинковичах",
    nameGenitive: "Калинковичей",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.1323, lng: 29.3257 },
    population: 36000,
  },
  {
    slug: "rogachev",
    name: "Рогачёв",
    namePrepositional: "Рогачёве",
    nameGenitive: "Рогачёва",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 53.0934, lng: 30.0495 },
    population: 34000,
  },
  {
    slug: "dobrush",
    name: "Добруш",
    namePrepositional: "Добруше",
    nameGenitive: "Добруша",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.4089, lng: 31.3237 },
    population: 18000,
  },
  {
    slug: "khoyniki",
    name: "Хойники",
    namePrepositional: "Хойниках",
    nameGenitive: "Хойников",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 51.8914, lng: 29.9552 },
    population: 14000,
  },
  {
    slug: "petrikov",
    name: "Петриков",
    namePrepositional: "Петрикове",
    nameGenitive: "Петрикова",
    oblast: "Гомельская область",
    oblastGenitive: "Гомельской области",
    coords: { lat: 52.1286, lng: 28.4927 },
    population: 10000,
  },
  {
    slug: "minsk",
    name: "Минск",
    namePrepositional: "Минске",
    nameGenitive: "Минска",
    oblast: "Минск и Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 53.9006, lng: 27.559 },
    districts: [
      "Центральный",
      "Советский",
      "Первомайский",
      "Партизанский",
      "Заводской",
      "Ленинский",
      "Октябрьский",
      "Московский",
      "Фрунзенский",
    ],
    population: 1997000,
  },
  {
    slug: "borisov",
    name: "Борисов",
    namePrepositional: "Борисове",
    nameGenitive: "Борисова",
    oblast: "Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 54.2279, lng: 28.505 },
    population: 135000,
  },
  {
    slug: "soligorsk",
    name: "Солигорск",
    namePrepositional: "Солигорске",
    nameGenitive: "Солигорска",
    oblast: "Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 52.7876, lng: 27.5415 },
    population: 103000,
  },
  {
    slug: "molodechno",
    name: "Молодечно",
    namePrepositional: "Молодечно",
    nameGenitive: "Молодечно",
    oblast: "Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 54.3073, lng: 26.8388 },
    population: 94000,
  },
  {
    slug: "zhodino",
    name: "Жодино",
    namePrepositional: "Жодино",
    nameGenitive: "Жодино",
    oblast: "Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 54.0985, lng: 28.3336 },
    population: 63000,
  },
  {
    slug: "slutsk",
    name: "Слуцк",
    namePrepositional: "Слуцке",
    nameGenitive: "Слуцка",
    oblast: "Минская область",
    oblastGenitive: "Минской области",
    coords: { lat: 53.0274, lng: 27.5597 },
    population: 61000,
  },
  {
    slug: "brest",
    name: "Брест",
    namePrepositional: "Бресте",
    nameGenitive: "Бреста",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 52.0976, lng: 23.7341 },
    population: 346000,
  },
  {
    slug: "baranovichi",
    name: "Барановичи",
    namePrepositional: "Барановичах",
    nameGenitive: "Барановичей",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 53.1327, lng: 26.0139 },
    population: 171000,
  },
  {
    slug: "pinsk",
    name: "Пинск",
    namePrepositional: "Пинске",
    nameGenitive: "Пинска",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 52.1229, lng: 26.0951 },
    population: 124000,
  },
  {
    slug: "kobrin",
    name: "Кобрин",
    namePrepositional: "Кобрине",
    nameGenitive: "Кобрина",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 52.214, lng: 24.3564 },
    population: 52000,
  },
  {
    slug: "bereza",
    name: "Берёза",
    namePrepositional: "Берёзе",
    nameGenitive: "Берёзы",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 52.5317, lng: 24.9786 },
    population: 29000,
  },
  {
    slug: "zhabinka",
    name: "Жабинка",
    namePrepositional: "Жабинке",
    nameGenitive: "Жабинки",
    oblast: "Брестская область",
    oblastGenitive: "Брестской области",
    coords: { lat: 52.1984, lng: 24.0115 },
    population: 13000,
  },
  {
    slug: "grodno",
    name: "Гродно",
    namePrepositional: "Гродно",
    nameGenitive: "Гродно",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 53.6694, lng: 23.8131 },
    population: 364000,
  },
  {
    slug: "lida",
    name: "Лида",
    namePrepositional: "Лиде",
    nameGenitive: "Лиды",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 53.8916, lng: 25.3027 },
    population: 101000,
  },
  {
    slug: "volkovysk",
    name: "Волковыск",
    namePrepositional: "Волковыске",
    nameGenitive: "Волковыска",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 53.1512, lng: 24.4513 },
    population: 44000,
  },
  {
    slug: "slonim",
    name: "Слоним",
    namePrepositional: "Слониме",
    nameGenitive: "Слонима",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 53.0869, lng: 25.3163 },
    population: 48000,
  },
  {
    slug: "smorgon",
    name: "Сморгонь",
    namePrepositional: "Сморгони",
    nameGenitive: "Сморгони",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 54.4814, lng: 26.3934 },
    population: 35000,
  },
  {
    slug: "novogrudok",
    name: "Новогрудок",
    namePrepositional: "Новогрудке",
    nameGenitive: "Новогрудка",
    oblast: "Гродненская область",
    oblastGenitive: "Гродненской области",
    coords: { lat: 53.5942, lng: 25.8191 },
    population: 27000,
  },
  {
    slug: "vitebsk",
    name: "Витебск",
    namePrepositional: "Витебске",
    nameGenitive: "Витебска",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 55.1848, lng: 30.2016 },
    population: 358000,
  },
  {
    slug: "orsha",
    name: "Орша",
    namePrepositional: "Орше",
    nameGenitive: "Орши",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 54.5081, lng: 30.4172 },
    population: 108000,
  },
  {
    slug: "novopolotsk",
    name: "Новополоцк",
    namePrepositional: "Новополоцке",
    nameGenitive: "Новополоцка",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 55.5318, lng: 28.5987 },
    population: 99000,
  },
  {
    slug: "polotsk",
    name: "Полоцк",
    namePrepositional: "Полоцке",
    nameGenitive: "Полоцка",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 55.4859, lng: 28.7686 },
    population: 82000,
  },
  {
    slug: "glubokoe",
    name: "Глубокое",
    namePrepositional: "Глубоком",
    nameGenitive: "Глубокого",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 55.1384, lng: 27.6879 },
    population: 18000,
  },
  {
    slug: "lepel",
    name: "Лепель",
    namePrepositional: "Лепеле",
    nameGenitive: "Лепеля",
    oblast: "Витебская область",
    oblastGenitive: "Витебской области",
    coords: { lat: 54.8818, lng: 28.699 },
    population: 17000,
  },
  {
    slug: "mogilev",
    name: "Могилёв",
    namePrepositional: "Могилёве",
    nameGenitive: "Могилёва",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 53.9023, lng: 30.3307 },
    population: 353000,
  },
  {
    slug: "bobruysk",
    name: "Бобруйск",
    namePrepositional: "Бобруйске",
    nameGenitive: "Бобруйска",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 53.1384, lng: 29.2214 },
    population: 206000,
  },
  {
    slug: "osipovichi",
    name: "Осиповичи",
    namePrepositional: "Осиповичах",
    nameGenitive: "Осиповичей",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 53.3011, lng: 28.6426 },
    population: 29000,
  },
  {
    slug: "gorki",
    name: "Горки",
    namePrepositional: "Горках",
    nameGenitive: "Горок",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 54.286, lng: 30.9866 },
    population: 29000,
  },
  {
    slug: "krichev",
    name: "Кричев",
    namePrepositional: "Кричеве",
    nameGenitive: "Кричева",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 53.7125, lng: 31.7099 },
    population: 23000,
  },
  {
    slug: "klimovichi",
    name: "Климовичи",
    namePrepositional: "Климовичах",
    nameGenitive: "Климовичей",
    oblast: "Могилёвская область",
    oblastGenitive: "Могилёвской области",
    coords: { lat: 53.6071, lng: 31.9565 },
    population: 15000,
  },
];

export const getCityBySlug = (slug: string) =>
  cities.find((city) => city.slug === slug);
